FROM openjdk:8
WORKDIR /home

ENV var=${var}

ENV MAIN_PATH=/srv
ENV APK_DIR=${MAIN_PATH}/apks
ENV ANDROID_PLATFORMS=${MAIN_PATH}/android-platforms
ENV SDK=${MAIN_PATH}/sdk
ENV INSTRUMENTED=${MAIN_PATH}/instrumented

#CMD java -jar static-0.2.0.jar -c main.json -a ${APK_DIR}/$var
CMD tail -f /dev/null
